# Generated by Django 4.1.9 on 2023-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enasInventory", "0002_book_delete_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="quantity_needed",
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
