# Generated by Django 4.1.9 on 2023-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enasInventory", "0003_book_book_name_book_isbn_book_quantity_needed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="quantity_needed", field=models.IntegerField(),
        ),
    ]
