# Generated by Django 4.1.9 on 2023-06-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enasInventory", "0004_alter_book_quantity_needed"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="date_requested",
            field=models.DateTimeField(default='2023-06-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="order_status",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="year_group",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
