# Generated by Django 4.1.9 on 2023-07-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enasInventory", "0005_book_date_requested_book_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quantity_received",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
