# Generated by Django 4.1.9 on 2023-07-10 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("enasInventory", "0007_bookreceived_student_bookreceived_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreceived",
            name="date_received",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
