# Generated by Django 4.1.9 on 2023-07-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enasInventory", "0008_bookreceived_date_received"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookreceived", name="students",),
        migrations.AddField(
            model_name="bookreceived",
            name="student",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="enasInventory.student",
            ),
            preserve_default=False,
        ),
    ]
