# Generated by Django 3.2.20 on 2024-03-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enasInventory', '0009_remove_bookreceived_students_bookreceived_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreceived',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreceived',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='books_received',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookReceived',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
